remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Thomas Georges 
description: "Contact: Thomas.georges.pro@gmail.com"
show_downloads: false
logo: /assets/img/GEORGES_Thomas_02_colors_small.jpg
